name: Spleef
version: 2.2.10
author: Naruse
main: fr.naruse.spleef.main.SpleefPlugin
softdepend: [DBAPI, Vault, HolographicDisplays, PlaceholderAPI, SecondThreadAPI, DecentHolograms]
commands:
  spleef:
    description: All commands for Spleef